/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package greenwichcabs;

/**
 *
 * @author user
 */
public class DriverForm extends javax.swing.JPanel {

    /**
     * Creates new form DriverForm
     */
    public DriverForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelForDriverLastName = new javax.swing.JLabel();
        driverLastName = new javax.swing.JFormattedTextField();
        labelForDriverSSN = new javax.swing.JLabel();
        driverSSN = new javax.swing.JTextField();
        saveNewDriverFormButton = new javax.swing.JButton();
        cancelAddDriverFormButton = new javax.swing.JButton();
        labelForDriverFirstName = new javax.swing.JLabel();
        driverFirstName = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(122, 72, 221));
        setPreferredSize(new java.awt.Dimension(550, 430));

        labelForDriverLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelForDriverLastName.setForeground(new java.awt.Color(255, 255, 255));
        labelForDriverLastName.setLabelFor(driverLastName);
        labelForDriverLastName.setText("Last Name");

        driverLastName.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        driverLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLastNameActionPerformed(evt);
            }
        });

        labelForDriverSSN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelForDriverSSN.setForeground(new java.awt.Color(255, 255, 255));
        labelForDriverSSN.setLabelFor(driverSSN);
        labelForDriverSSN.setText("SSN");

        driverSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverSSN.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));

        saveNewDriverFormButton.setBackground(new java.awt.Color(64, 43, 100));
        saveNewDriverFormButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveNewDriverFormButton.setForeground(new java.awt.Color(255, 255, 255));
        saveNewDriverFormButton.setText("Save");
        saveNewDriverFormButton.setBorder(null);
        saveNewDriverFormButton.setBorderPainted(false);

        cancelAddDriverFormButton.setBackground(new java.awt.Color(64, 43, 100));
        cancelAddDriverFormButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelAddDriverFormButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelAddDriverFormButton.setText("Cancel");
        cancelAddDriverFormButton.setBorder(null);
        cancelAddDriverFormButton.setBorderPainted(false);

        labelForDriverFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelForDriverFirstName.setForeground(new java.awt.Color(255, 255, 255));
        labelForDriverFirstName.setLabelFor(driverLastName);
        labelForDriverFirstName.setText("First Name");

        driverFirstName.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        driverFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverFirstNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(cancelAddDriverFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(saveNewDriverFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelForDriverLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(driverLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelForDriverSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(driverSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelForDriverFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(driverFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelForDriverLastName, labelForDriverSSN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelForDriverFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelForDriverLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForDriverSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddDriverFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewDriverFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelForDriverLastName, labelForDriverSSN});

    }// </editor-fold>//GEN-END:initComponents

    private void driverLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverLastNameActionPerformed

    private void driverFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverFirstNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAddDriverFormButton;
    private javax.swing.JFormattedTextField driverFirstName;
    private javax.swing.JFormattedTextField driverLastName;
    private javax.swing.JTextField driverSSN;
    private javax.swing.JLabel labelForDriverFirstName;
    private javax.swing.JLabel labelForDriverLastName;
    private javax.swing.JLabel labelForDriverSSN;
    private javax.swing.JButton saveNewDriverFormButton;
    // End of variables declaration//GEN-END:variables
}
