/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package greenwichcabs;

import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        customInitForComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        newJourneyButton1 = new javax.swing.JPanel();
        newJourneyIcon1 = new javax.swing.JLabel();
        newJourneyLabel1 = new javax.swing.JLabel();
        addDriverButton = new javax.swing.JPanel();
        addDriverIcon = new javax.swing.JLabel();
        addDriverLabel = new javax.swing.JLabel();
        editJourneyButton = new javax.swing.JPanel();
        editJourneyIcon = new javax.swing.JLabel();
        editJourneyLabel = new javax.swing.JLabel();
        totalOfTheDayButton = new javax.swing.JPanel();
        totalOfTheDayIcon = new javax.swing.JLabel();
        totalOfTheDayLabel = new javax.swing.JLabel();
        appTitle = new javax.swing.JLabel();
        appTitleUnderline = new javax.swing.JSeparator();
        windowButtons = new javax.swing.JPanel();
        windowCloseButton = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);

        container.setMaximumSize(new java.awt.Dimension(800, 500));
        container.setMinimumSize(new java.awt.Dimension(800, 500));
        container.setPreferredSize(new java.awt.Dimension(800, 500));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(54, 33, 89));
        sidePane.setMaximumSize(new java.awt.Dimension(200, 500));
        sidePane.setPreferredSize(new java.awt.Dimension(200, 500));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newJourneyButton1.setBackground(new java.awt.Color(85, 65, 111));

        newJourneyIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_commute_white_18dp.png"))); // NOI18N

        newJourneyLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newJourneyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        newJourneyLabel1.setText("New Journey");
        newJourneyLabel1.setToolTipText("Record new journey");

        javax.swing.GroupLayout newJourneyButton1Layout = new javax.swing.GroupLayout(newJourneyButton1);
        newJourneyButton1.setLayout(newJourneyButton1Layout);
        newJourneyButton1Layout.setHorizontalGroup(
            newJourneyButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJourneyButton1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newJourneyIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newJourneyLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        newJourneyButton1Layout.setVerticalGroup(
            newJourneyButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newJourneyButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newJourneyButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(newJourneyIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newJourneyLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );

        sidePane.add(newJourneyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 50));

        addDriverButton.setBackground(new java.awt.Color(64, 43, 100));

        addDriverIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_account_circle_white_18dp.png"))); // NOI18N

        addDriverLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDriverLabel.setForeground(new java.awt.Color(255, 255, 255));
        addDriverLabel.setText("Add Driver");
        addDriverLabel.setToolTipText("Record new journey");

        javax.swing.GroupLayout addDriverButtonLayout = new javax.swing.GroupLayout(addDriverButton);
        addDriverButton.setLayout(addDriverButtonLayout);
        addDriverButtonLayout.setHorizontalGroup(
            addDriverButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDriverButtonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addDriverIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDriverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        addDriverButtonLayout.setVerticalGroup(
            addDriverButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDriverButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDriverButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addDriverIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDriverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePane.add(addDriverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        editJourneyButton.setBackground(new java.awt.Color(64, 43, 100));

        editJourneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_edit_white_18dp.png"))); // NOI18N

        editJourneyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editJourneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        editJourneyLabel.setText("Edit Journey");
        editJourneyLabel.setToolTipText("Record new journey");

        javax.swing.GroupLayout editJourneyButtonLayout = new javax.swing.GroupLayout(editJourneyButton);
        editJourneyButton.setLayout(editJourneyButtonLayout);
        editJourneyButtonLayout.setHorizontalGroup(
            editJourneyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editJourneyButtonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(editJourneyIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editJourneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        editJourneyButtonLayout.setVerticalGroup(
            editJourneyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editJourneyButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editJourneyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(editJourneyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editJourneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePane.add(editJourneyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        totalOfTheDayButton.setBackground(new java.awt.Color(64, 43, 100));

        totalOfTheDayIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_dashboard_white_18dp.png"))); // NOI18N

        totalOfTheDayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalOfTheDayLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalOfTheDayLabel.setText("Total of The Day");
        totalOfTheDayLabel.setToolTipText("Record new journey");

        javax.swing.GroupLayout totalOfTheDayButtonLayout = new javax.swing.GroupLayout(totalOfTheDayButton);
        totalOfTheDayButton.setLayout(totalOfTheDayButtonLayout);
        totalOfTheDayButtonLayout.setHorizontalGroup(
            totalOfTheDayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalOfTheDayButtonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(totalOfTheDayIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalOfTheDayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        totalOfTheDayButtonLayout.setVerticalGroup(
            totalOfTheDayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalOfTheDayButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalOfTheDayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(totalOfTheDayIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalOfTheDayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePane.add(totalOfTheDayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        appTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        appTitle.setForeground(new java.awt.Color(255, 255, 255));
        appTitle.setText("Greenwich Cabs");
        sidePane.add(appTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 40));
        sidePane.add(appTitleUnderline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 210, 10));

        container.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 249, -1));

        windowButtons.setMaximumSize(new java.awt.Dimension(50, 50));
        windowButtons.setMinimumSize(new java.awt.Dimension(25, 25));
        windowButtons.setPreferredSize(new java.awt.Dimension(50, 50));
        windowButtons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                windowButtonsMouseClicked(evt);
            }
        });

        windowCloseButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        windowCloseButton.setForeground(new java.awt.Color(122, 72, 221));
        windowCloseButton.setText("X");
        windowCloseButton.setToolTipText("close");
        windowCloseButton.setAlignmentX(0.5F);
        windowCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        windowCloseButton.setMaximumSize(new java.awt.Dimension(30, 30));
        windowCloseButton.setMinimumSize(new java.awt.Dimension(30, 30));
        windowCloseButton.setPreferredSize(new java.awt.Dimension(30, 30));
        windowCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                windowCloseButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout windowButtonsLayout = new javax.swing.GroupLayout(windowButtons);
        windowButtons.setLayout(windowButtonsLayout);
        windowButtonsLayout.setHorizontalGroup(
            windowButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        windowButtonsLayout.setVerticalGroup(
            windowButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(windowCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        container.add(windowButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        content.setBackground(new java.awt.Color(122, 72, 221));
        content.setMaximumSize(new java.awt.Dimension(600, 450));
        content.setMinimumSize(new java.awt.Dimension(600, 450));
        content.setPreferredSize(new java.awt.Dimension(600, 450));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        container.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 68, 551, 432));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInitForComponents() {
        windowCloseButton.setHorizontalAlignment(JLabel.CENTER);
    }
    private void windowButtonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowButtonsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_windowButtonsMouseClicked

    private void windowCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowCloseButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_windowCloseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDriverButton;
    private javax.swing.JLabel addDriverIcon;
    private javax.swing.JLabel addDriverLabel;
    private javax.swing.JLabel appTitle;
    private javax.swing.JSeparator appTitleUnderline;
    private javax.swing.JPanel container;
    private javax.swing.JPanel content;
    private javax.swing.JPanel editJourneyButton;
    private javax.swing.JLabel editJourneyIcon;
    private javax.swing.JLabel editJourneyLabel;
    private javax.swing.JPanel newJourneyButton1;
    private javax.swing.JLabel newJourneyIcon1;
    private javax.swing.JLabel newJourneyLabel1;
    private javax.swing.JPanel sidePane;
    private javax.swing.JPanel totalOfTheDayButton;
    private javax.swing.JLabel totalOfTheDayIcon;
    private javax.swing.JLabel totalOfTheDayLabel;
    private javax.swing.JPanel windowButtons;
    private javax.swing.JLabel windowCloseButton;
    // End of variables declaration//GEN-END:variables
}
